### ISSUE TITLE
NAHHHHHHHHHH

### ISSUE THREAD

**Issue by Milxnor** [Trail-Blaze/Otto#15]
![image](https://user-images.githubusercontent.com/84999745/165289527-cc7b8de8-2ae2-4447-9124-2d0f17bf1332.png)
AREYOu SAYING NEONITE HAS VIRUSES IN IT LMAO??? Ok storm idk probably not but NEONITE?>!?!?

**Comment by vinzy2** [comment]
probably knowing them lol
